In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [8]:
df = pd.read_csv("homeprices.csv")

In [9]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [12]:
import math
median_bedrooms = math.floor(df.bedrooms.median())

In [13]:
median_bedrooms

4

In [16]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [17]:
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [18]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression()

In [19]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [20]:
reg.intercept_

np.float64(221323.00186540402)

In [21]:
reg.predict([[3000, 3, 40]])

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([498408.25158031])

In [22]:
reg.predict([[2500, 4, 5]])

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([578876.03748933])

In [1]:
import pickle

In [3]:
with open('model_pickle', 'wb') as f: 
    pickle.dump(reg, f)

NameError: name 'reg' is not defined